### ISSUE TITLE
New 2.4 API is still marked Beta

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#219]
Error starting driver: This is a Beta API. You must flag your extensions as using Beta API.
This is a Beta API. You must flag your extensions as using Beta API.
fXL: This is a Beta API. You must flag your extensions as using Beta API.
    at RdT.pxf(SourceFile:285)
    at TAr.betaApi(SourceFile:151)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost.betaApi(SourceFile:126)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost.loadSVG(SourceFile:1148)
    at de.mossgrabers.bitwig.framework.daw.HostImpl.loadSVG(HostImpl.java:200)
    at de.mossgrabers.framework.daw.resource.ResourceHandler.addSVGImage(ResourceHandler.java:82)
    at de.mossgrabers.framework.daw.resource.ResourceHandler.init(ResourceHandler.java:34)
    at de.mossgrabers.framework.graphics.display.VirtualDisplay.<init>(VirtualDisplay.java:47)
    at de.mossgrabers.controller.push.controller.PushDisplay.<init>(PushDisplay.java:106)
    at de.mossgrabers.controller.push.PushControllerSetup.createDisplay(PushControllerSetup.java:234)
    at de.mossgrabers.controller.push.PushControllerSetup.createSurface(PushControllerSetup.java:227)
    at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:107)
    at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
    at TD.CAQ(SourceFile:19)
    at zfz.bKU(SourceFile:57)
    at lWS.fMA(SourceFile:237)
    at lWS.OEu(SourceFile:164)
    at lWS.<init>(SourceFile:127)
    at mlO.OEu(SourceFile:251)
    at mlO.mgN(SourceFile:343)
    at mlO.mgN(SourceFile:202)
    at fB.run(SourceFile:91)
    at mlO.run(SourceFile:102)

**Comment by git-moss** [comment]
That's intentinal, since some features have problems on specific platforms.
