### ISSUE TITLE
Regression: Clip.toggleStep requires API 10 but is available since API 1

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#229]
This cannot be called when specifying required API version 7:
This is only availble for API versions after 10
Tuo: This cannot be called when specifying required API version 7:
This is only availble for API versions after 10
    at jFV.tTy(SourceFile:279)
    at Nxo.newSince(SourceFile:146)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost.newSince(SourceFile:143)
    at com.bitwig.flt.control_surface.proxy.ControlSurfaceObject.newSince(SourceFile:298)
    at com.bitwig.flt.control_surface.proxy.ClipProxy.toggleStep(SourceFile:364)
    at com.bitwig.flt.control_surface.proxy.ClipProxy.toggleStep(SourceFile:358)
    at com.bitwig.flt.control_surface.proxy.DelegatingClipProxy.toggleStep(SourceFile:140)
    at de.mossgrabers.bitwig.framework.daw.CursorClipImpl.toggleStep(CursorClipImpl.java:383)
    at de.mossgrabers.framework.view.AbstractNoteSequencerView.onGridNote(AbstractNoteSequencerView.java:102)
    at de.mossgrabers.framework.controller.AbstractControlSurface.handleGridNote(AbstractControlSurface.java:934)
    at de.mossgrabers.framework.controller.AbstractControlSurface.handleNote(AbstractControlSurface.java:807)
    at de.mossgrabers.framework.controller.AbstractControlSurface.handleMidi(AbstractControlSurface.java:763)
    at xkq.WwW(SourceFile:199)
    at FI.WwW(SourceFile:804)
    at Wqx.WwW(SourceFile:695)
    at BsA.WwW(SourceFile:107)
    at qoV.WwW(SourceFile:61)
    at zDx.WwW(SourceFile:33)
    at wzq.WwW(SourceFile:1066)
    at BsA.KUW(SourceFile:55)
    at Oge.WwW(SourceFile:215)
    at Nto.tTy(SourceFile:202)
    at ZTr.run(SourceFile:91)
    at Nto.run(SourceFile:102)

**Comment by abique** [comment]
Should be fixed in beta 3.

**Comment by git-moss** [comment]
Fixed.
