### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#243]
I get a crash after some restarts of my extension. Could be a memory leak with Clips?!
Works fine again after restarting Bitwig.

**To reproduce simply start and stop the "Push 2" extension several times**.

Java heap space
java.lang.OutOfMemoryError: Java heap space
    at de.mossgrabers.bitwig.framework.daw.CursorClipImpl.<init>(CursorClipImpl.java:66)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl.lambda$1(ModelImpl.java:211)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl$$Lambda$1804/0x0000000102505040.apply(Unknown Source)
    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl.getNoteClip(ModelImpl.java:211)
    at de.mossgrabers.framework.view.AbstractSequencerView.getClip(AbstractSequencerView.java:165)
    at de.mossgrabers.framework.view.AbstractSequencerView.<init>(AbstractSequencerView.java:101)
    at de.mossgrabers.framework.view.AbstractSequencerView.<init>(AbstractSequencerView.java:74)
    at de.mossgrabers.framework.view.AbstractRaindropsView.<init>(AbstractRaindropsView.java:48)
    at de.mossgrabers.controller.push.view.RaindropsView.<init>(RaindropsView.java:30)
    at de.mossgrabers.controller.push.PushControllerSetup.createViews(PushControllerSetup.java:418)
    at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:113)
    at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
    at WsY.zEv(SourceFile:19)
    at kI1.S3(SourceFile:57)
    at tHv.Oyk(SourceFile:245)
    at tHv.cn(SourceFile:161)
    at tHv.<init>(SourceFile:128)
    at yLe.cn(SourceFile:247)
    at yLe.hNn(SourceFile:339)
    at yLe$$Lambda$843/0x0000000102766c40.run(Unknown Source)
    at yLe.hNn(SourceFile:198)
    at go.run(SourceFile:91)
    at yLe.run(SourceFile:102)

**Comment by NickJAllen** [comment]
Should be fixed in 83939

**Comment by git-moss** [comment]
Fixed.
